/*
 * Copyright 2018 Confluent Inc.
 *
 * Licensed under the Confluent Community License (the "License"); you may not use
 * this file except in compliance with the License.  You may obtain a copy of the
 * License at
 *
 * http://www.confluent.io/confluent-community-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

package io.confluent.connect.jdbc.integration;

import io.confluent.connect.jdbc.JdbcSourceConnector;
import io.confluent.connect.jdbc.source.JdbcSourceConnectorConfig;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.testcontainers.containers.OracleContainer;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Oracle run of the shared source connector mode matrix (bulk, incrementing, timestamp, and
 * timestamp+incrementing) defined in {@link AbstractJdbcSourceConnectorIT}.
 */
public class OracleJdbcSourceConnectorIT extends AbstractJdbcSourceConnectorIT {

  @ClassRule
  @SuppressWarnings("deprecation")
  public static final OracleContainer oracle = new OracleContainer();

  @BeforeClass
  public static void setupClass() throws SQLException {
    connection = DriverManager.getConnection(
        oracle.getJdbcUrl(),
        oracle.getUsername(),
        oracle.getPassword()
    );
  }

  @AfterClass
  public static void teardownClass() throws SQLException {
    if (connection != null && !connection.isClosed()) {
      connection.close();
    }
  }

  @Before
  public void setup() throws SQLException {
    super.setup();
    props.put(JdbcSourceConnectorConfig.DB_TIMEZONE_CONFIG, "UTC");
  }

  @Override
  protected DatabaseTestConfig getDatabaseConfig() {
    return new DatabaseTestConfig(
        oracle.getJdbcUrl(),
        oracle.getUsername(),
        oracle.getPassword(),
        "OracleDatabaseDialect"
    );
  }

  @Override
  protected Class<?> getSourceConnectorClass() {
    return JdbcSourceConnector.class;
  }

  @Override
  protected String getConnectorName() {
    return "oracle-source-connector";
  }

  @Override
  protected boolean needsUpperCaseIdentifiers() {
    return true;
  }

  @Override
  protected String getTopicPrefix() {
    return "test-oracle-";
  }

  @Override
  protected void createTable(String tableName) throws SQLException {
    try (Statement stmt = connection.createStatement()) {
      stmt.execute("CREATE TABLE " + tableName + " ("
          + "id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
          + "name VARCHAR2(100), "
          + "value VARCHAR2(100), "
          + "updated_at TIMESTAMP DEFAULT CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP)"
          + ")");
    }
  }

  @Override
  protected void updateRecordTimestamp(String tableName, int id) throws SQLException {
    try (Statement stmt = connection.createStatement()) {
      stmt.execute(String.format(
          "UPDATE %s SET name = 'name_%d_updated', "
              + "updated_at = CAST(CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP) "
              + "WHERE id = %d",
          tableName, id, id));
    }
  }
}
