// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface CloseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.CloseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session session = 1;</code>
   */
  boolean hasSession();
  /**
   * <code>.api.Session session = 1;</code>
   */
  Session getSession();
  /**
   * <code>.api.Session session = 1;</code>
   */
  SessionOrBuilder getSessionOrBuilder();

  /**
   * <pre>
   * -1: returns all, 0: nothing, &gt;0: max rows
   * </pre>
   *
   * <code>int32 MaxErrorRows = 2;</code>
   */
  int getMaxErrorRows();

  /**
   * <code>bool Abort = 3;</code>
   */
  boolean getAbort();
}
