// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface ConnectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ConnectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Host address of Greenplum coordinator; must be accessible from gpss server system
   * </pre>
   *
   * <code>string Host = 1;</code>
   */
  String getHost();
  /**
   * <pre>
   * Host address of Greenplum coordinator; must be accessible from gpss server system
   * </pre>
   *
   * <code>string Host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <pre>
   * Greenplum coordinator port
   * </pre>
   *
   * <code>int32 Port = 2;</code>
   */
  int getPort();

  /**
   * <pre>
   * User or role name that gpss uses to access Greenplum
   * </pre>
   *
   * <code>string Username = 3;</code>
   */
  String getUsername();
  /**
   * <pre>
   * User or role name that gpss uses to access Greenplum
   * </pre>
   *
   * <code>string Username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * User password
   * </pre>
   *
   * <code>string Password = 4;</code>
   */
  String getPassword();
  /**
   * <pre>
   * User password
   * </pre>
   *
   * <code>string Password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   * Database name
   * </pre>
   *
   * <code>string DB = 5;</code>
   */
  String getDB();
  /**
   * <pre>
   * Database name
   * </pre>
   *
   * <code>string DB = 5;</code>
   */
  com.google.protobuf.ByteString
      getDBBytes();

  /**
   * <pre>
   * Use SSL or not; ignored, use the gpss config file to config SSL
   * </pre>
   *
   * <code>bool UseSSL = 6;</code>
   */
  boolean getUseSSL();

  /**
   * <pre>
   * Release the session after idle for specified number of seconds
   * </pre>
   *
   * <code>int32 SessionTimeout = 7;</code>
   */
  int getSessionTimeout();
}
