// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface DescribeTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.DescribeTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.Session Session = 1;</code>
   */
  boolean hasSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  Session getSession();
  /**
   * <code>.api.Session Session = 1;</code>
   */
  SessionOrBuilder getSessionOrBuilder();

  /**
   * <code>string SchemaName = 2;</code>
   */
  String getSchemaName();
  /**
   * <code>string SchemaName = 2;</code>
   */
  com.google.protobuf.ByteString
      getSchemaNameBytes();

  /**
   * <code>string TableName = 3;</code>
   */
  String getTableName();
  /**
   * <code>string TableName = 3;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();
}
