// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface FormatDelimitedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.FormatDelimited)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The source column names
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  java.util.List<IntermediateColumn> 
      getColumnsList();
  /**
   * <pre>
   * The source column names
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  IntermediateColumn getColumns(int index);
  /**
   * <pre>
   * The source column names
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <pre>
   * The source column names
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  java.util.List<? extends IntermediateColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <pre>
   * The source column names
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  IntermediateColumnOrBuilder getColumnsOrBuilder(
      int index);

  /**
   * <code>string delimiter = 2;</code>
   */
  String getDelimiter();
  /**
   * <code>string delimiter = 2;</code>
   */
  com.google.protobuf.ByteString
      getDelimiterBytes();
}
