// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface FormatJSONOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.FormatJSON)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The source column name
   * </pre>
   *
   * <code>.api.IntermediateColumn column = 1;</code>
   */
  boolean hasColumn();
  /**
   * <pre>
   * The source column name
   * </pre>
   *
   * <code>.api.IntermediateColumn column = 1;</code>
   */
  IntermediateColumn getColumn();
  /**
   * <pre>
   * The source column name
   * </pre>
   *
   * <code>.api.IntermediateColumn column = 1;</code>
   */
  IntermediateColumnOrBuilder getColumnOrBuilder();
}
