// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

/**
 * Protobuf type {@code FormatCSV}
 */
public  final class FormatCSV extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.FormatCSV)
    FormatCSVOrBuilder {
  // Use FormatCSV.newBuilder() to construct.
  private FormatCSV(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FormatCSV() {
    columns_ = java.util.Collections.emptyList();
    delimiter_ = "";
    quote_ = "";
    null_ = "";
    escape_ = "";
    forceNotNull_ = "";
    newline_ = "";
    fillMissingFields_ = false;
    header_ = false;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FormatCSV(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              columns_ = new java.util.ArrayList<IntermediateColumn>();
              mutable_bitField0_ |= 0x00000001;
            }
            columns_.add(
                input.readMessage (IntermediateColumn.parser(), extensionRegistry));
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            delimiter_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            quote_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            null_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            escape_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            forceNotNull_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            newline_ = s;
            break;
          }
          case 64: {

            fillMissingFields_ = input.readBool();
            break;
          }
          case 72: {

            header_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        columns_ = java.util.Collections.unmodifiableList(columns_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GpssOuterClass.internal_static_api_FormatCSV_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GpssOuterClass.internal_static_api_FormatCSV_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FormatCSV.class, FormatCSV.Builder.class);
  }

  private int bitField0_;
  public static final int COLUMNS_FIELD_NUMBER = 1;
  private java.util.List<IntermediateColumn> columns_;
  /**
   * <pre>
   * Source column, move to format.Column c1:bin, c2:json ...
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  public java.util.List<IntermediateColumn> getColumnsList() {
    return columns_;
  }
  /**
   * <pre>
   * Source column, move to format.Column c1:bin, c2:json ...
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  public java.util.List<? extends IntermediateColumnOrBuilder> 
      getColumnsOrBuilderList() {
    return columns_;
  }
  /**
   * <pre>
   * Source column, move to format.Column c1:bin, c2:json ...
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <pre>
   * Source column, move to format.Column c1:bin, c2:json ...
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  public IntermediateColumn getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <pre>
   * Source column, move to format.Column c1:bin, c2:json ...
   * </pre>
   *
   * <code>repeated .api.IntermediateColumn columns = 1;</code>
   */
  public IntermediateColumnOrBuilder getColumnsOrBuilder(
      int index) {
    return columns_.get(index);
  }

  public static final int DELIMITER_FIELD_NUMBER = 2;
  private volatile Object delimiter_;
  /**
   * <code>string delimiter = 2;</code>
   */
  public String getDelimiter() {
    Object ref = delimiter_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      delimiter_ = s;
      return s;
    }
  }
  /**
   * <code>string delimiter = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDelimiterBytes() {
    Object ref = delimiter_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      delimiter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTE_FIELD_NUMBER = 3;
  private volatile Object quote_;
  /**
   * <code>string quote = 3;</code>
   */
  public String getQuote() {
    Object ref = quote_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      quote_ = s;
      return s;
    }
  }
  /**
   * <code>string quote = 3;</code>
   */
  public com.google.protobuf.ByteString
      getQuoteBytes() {
    Object ref = quote_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      quote_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NULL_FIELD_NUMBER = 4;
  private volatile Object null_;
  /**
   * <code>string null = 4;</code>
   */
  public String getNull() {
    Object ref = null_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      null_ = s;
      return s;
    }
  }
  /**
   * <code>string null = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNullBytes() {
    Object ref = null_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      null_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ESCAPE_FIELD_NUMBER = 5;
  private volatile Object escape_;
  /**
   * <code>string escape = 5;</code>
   */
  public String getEscape() {
    Object ref = escape_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      escape_ = s;
      return s;
    }
  }
  /**
   * <code>string escape = 5;</code>
   */
  public com.google.protobuf.ByteString
      getEscapeBytes() {
    Object ref = escape_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      escape_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORCE_NOT_NULL_FIELD_NUMBER = 6;
  private volatile Object forceNotNull_;
  /**
   * <code>string force_not_null = 6;</code>
   */
  public String getForceNotNull() {
    Object ref = forceNotNull_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      forceNotNull_ = s;
      return s;
    }
  }
  /**
   * <code>string force_not_null = 6;</code>
   */
  public com.google.protobuf.ByteString
      getForceNotNullBytes() {
    Object ref = forceNotNull_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      forceNotNull_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEWLINE_FIELD_NUMBER = 7;
  private volatile Object newline_;
  /**
   * <code>string newline = 7;</code>
   */
  public String getNewline() {
    Object ref = newline_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      newline_ = s;
      return s;
    }
  }
  /**
   * <code>string newline = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNewlineBytes() {
    Object ref = newline_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      newline_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILL_MISSING_FIELDS_FIELD_NUMBER = 8;
  private boolean fillMissingFields_;
  /**
   * <code>bool fill_missing_fields = 8;</code>
   */
  public boolean getFillMissingFields() {
    return fillMissingFields_;
  }

  public static final int HEADER_FIELD_NUMBER = 9;
  private boolean header_;
  /**
   * <code>bool header = 9;</code>
   */
  public boolean getHeader() {
    return header_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < columns_.size(); i++) {
      output.writeMessage(1, columns_.get(i));
    }
    if (!getDelimiterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, delimiter_);
    }
    if (!getQuoteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, quote_);
    }
    if (!getNullBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, null_);
    }
    if (!getEscapeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, escape_);
    }
    if (!getForceNotNullBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, forceNotNull_);
    }
    if (!getNewlineBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, newline_);
    }
    if (fillMissingFields_ != false) {
      output.writeBool(8, fillMissingFields_);
    }
    if (header_ != false) {
      output.writeBool(9, header_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < columns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, columns_.get(i));
    }
    if (!getDelimiterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, delimiter_);
    }
    if (!getQuoteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, quote_);
    }
    if (!getNullBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, null_);
    }
    if (!getEscapeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, escape_);
    }
    if (!getForceNotNullBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, forceNotNull_);
    }
    if (!getNewlineBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, newline_);
    }
    if (fillMissingFields_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, fillMissingFields_);
    }
    if (header_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, header_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FormatCSV)) {
      return super.equals(obj);
    }
    FormatCSV other =  (FormatCSV) obj;

    boolean result = true;
    result = result && getColumnsList()
        .equals(other.getColumnsList());
    result = result && getDelimiter()
        .equals(other.getDelimiter());
    result = result && getQuote()
        .equals(other.getQuote());
    result = result && getNull()
        .equals(other.getNull());
    result = result && getEscape()
        .equals(other.getEscape());
    result = result && getForceNotNull()
        .equals(other.getForceNotNull());
    result = result && getNewline()
        .equals(other.getNewline());
    result = result && (getFillMissingFields()
        == other.getFillMissingFields());
    result = result && (getHeader()
        == other.getHeader());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    hash = (37 * hash) + DELIMITER_FIELD_NUMBER;
    hash = (53 * hash) + getDelimiter().hashCode();
    hash = (37 * hash) + QUOTE_FIELD_NUMBER;
    hash = (53 * hash) + getQuote().hashCode();
    hash = (37 * hash) + NULL_FIELD_NUMBER;
    hash = (53 * hash) + getNull().hashCode();
    hash = (37 * hash) + ESCAPE_FIELD_NUMBER;
    hash = (53 * hash) + getEscape().hashCode();
    hash = (37 * hash) + FORCE_NOT_NULL_FIELD_NUMBER;
    hash = (53 * hash) + getForceNotNull().hashCode();
    hash = (37 * hash) + NEWLINE_FIELD_NUMBER;
    hash = (53 * hash) + getNewline().hashCode();
    hash = (37 * hash) + FILL_MISSING_FIELDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFillMissingFields());
    hash = (37 * hash) + HEADER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHeader());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FormatCSV parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FormatCSV parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FormatCSV parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FormatCSV parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FormatCSV parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FormatCSV parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FormatCSV parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FormatCSV parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FormatCSV parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FormatCSV parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FormatCSV parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FormatCSV parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder (FormatCSV prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FormatCSV}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.FormatCSV)
      FormatCSVOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GpssOuterClass.internal_static_api_FormatCSV_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GpssOuterClass.internal_static_api_FormatCSV_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FormatCSV.class, FormatCSV.Builder.class);
    }

    // Construct using FormatCSV.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getColumnsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        columnsBuilder_.clear();
      }
      delimiter_ = "";

      quote_ = "";

      null_ = "";

      escape_ = "";

      forceNotNull_ = "";

      newline_ = "";

      fillMissingFields_ = false;

      header_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GpssOuterClass.internal_static_api_FormatCSV_descriptor;
    }

    public FormatCSV getDefaultInstanceForType() {
      return FormatCSV.getDefaultInstance();
    }

    public FormatCSV build() {
      FormatCSV result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public FormatCSV buildPartial() {
      FormatCSV result = new FormatCSV(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (columnsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.columns_ = columns_;
      } else {
        result.columns_ = columnsBuilder_.build();
      }
      result.delimiter_ = delimiter_;
      result.quote_ = quote_;
      result.null_ = null_;
      result.escape_ = escape_;
      result.forceNotNull_ = forceNotNull_;
      result.newline_ = newline_;
      result.fillMissingFields_ = fillMissingFields_;
      result.header_ = header_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FormatCSV) {
        return mergeFrom( (FormatCSV)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom (FormatCSV other) {
      if (other == FormatCSV.getDefaultInstance()) return this;
      if (columnsBuilder_ == null) {
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
      } else {
        if (!other.columns_.isEmpty()) {
          if (columnsBuilder_.isEmpty()) {
            columnsBuilder_.dispose();
            columnsBuilder_ = null;
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
            columnsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColumnsFieldBuilder() : null;
          } else {
            columnsBuilder_.addAllMessages(other.columns_);
          }
        }
      }
      if (!other.getDelimiter().isEmpty()) {
        delimiter_ = other.delimiter_;
        onChanged();
      }
      if (!other.getQuote().isEmpty()) {
        quote_ = other.quote_;
        onChanged();
      }
      if (!other.getNull().isEmpty()) {
        null_ = other.null_;
        onChanged();
      }
      if (!other.getEscape().isEmpty()) {
        escape_ = other.escape_;
        onChanged();
      }
      if (!other.getForceNotNull().isEmpty()) {
        forceNotNull_ = other.forceNotNull_;
        onChanged();
      }
      if (!other.getNewline().isEmpty()) {
        newline_ = other.newline_;
        onChanged();
      }
      if (other.getFillMissingFields() != false) {
        setFillMissingFields(other.getFillMissingFields());
      }
      if (other.getHeader() != false) {
        setHeader(other.getHeader());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FormatCSV parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =  (FormatCSV) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<IntermediateColumn> columns_ =
      java.util.Collections.emptyList();
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        columns_ = new java.util.ArrayList<IntermediateColumn>(columns_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        IntermediateColumn, IntermediateColumn.Builder, IntermediateColumnOrBuilder> columnsBuilder_;

    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public java.util.List<IntermediateColumn> getColumnsList() {
      if (columnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columns_);
      } else {
        return columnsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public int getColumnsCount() {
      if (columnsBuilder_ == null) {
        return columns_.size();
      } else {
        return columnsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public IntermediateColumn getColumns(int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);
      } else {
        return columnsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder setColumns(
        int index, IntermediateColumn value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder setColumns(
        int index, IntermediateColumn.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder addColumns (IntermediateColumn value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder addColumns(
        int index, IntermediateColumn value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(index, value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder addColumns(
        IntermediateColumn.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder addColumns(
        int index, IntermediateColumn.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder addAllColumns(
        Iterable<? extends IntermediateColumn> values) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        onChanged();
      } else {
        columnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder clearColumns() {
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public Builder removeColumns(int index) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.remove(index);
        onChanged();
      } else {
        columnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public IntermediateColumn.Builder getColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public IntermediateColumnOrBuilder getColumnsOrBuilder(
        int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);  } else {
        return columnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public java.util.List<? extends IntermediateColumnOrBuilder> 
         getColumnsOrBuilderList() {
      if (columnsBuilder_ != null) {
        return columnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columns_);
      }
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public IntermediateColumn.Builder addColumnsBuilder() {
      return getColumnsFieldBuilder().addBuilder(
          IntermediateColumn.getDefaultInstance());
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public IntermediateColumn.Builder addColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().addBuilder(
          index, IntermediateColumn.getDefaultInstance());
    }
    /**
     * <pre>
     * Source column, move to format.Column c1:bin, c2:json ...
     * </pre>
     *
     * <code>repeated .api.IntermediateColumn columns = 1;</code>
     */
    public java.util.List<IntermediateColumn.Builder> 
         getColumnsBuilderList() {
      return getColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        IntermediateColumn, IntermediateColumn.Builder, IntermediateColumnOrBuilder> 
        getColumnsFieldBuilder() {
      if (columnsBuilder_ == null) {
        columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            IntermediateColumn, IntermediateColumn.Builder, IntermediateColumnOrBuilder>(
                columns_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        columns_ = null;
      }
      return columnsBuilder_;
    }

    private Object delimiter_ = "";
    /**
     * <code>string delimiter = 2;</code>
     */
    public String getDelimiter() {
      Object ref = delimiter_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        delimiter_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string delimiter = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDelimiterBytes() {
      Object ref = delimiter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        delimiter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string delimiter = 2;</code>
     */
    public Builder setDelimiter(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      delimiter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string delimiter = 2;</code>
     */
    public Builder clearDelimiter() {
      
      delimiter_ = getDefaultInstance().getDelimiter();
      onChanged();
      return this;
    }
    /**
     * <code>string delimiter = 2;</code>
     */
    public Builder setDelimiterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      delimiter_ = value;
      onChanged();
      return this;
    }

    private Object quote_ = "";
    /**
     * <code>string quote = 3;</code>
     */
    public String getQuote() {
      Object ref = quote_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        quote_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string quote = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQuoteBytes() {
      Object ref = quote_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        quote_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quote = 3;</code>
     */
    public Builder setQuote(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      quote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string quote = 3;</code>
     */
    public Builder clearQuote() {
      
      quote_ = getDefaultInstance().getQuote();
      onChanged();
      return this;
    }
    /**
     * <code>string quote = 3;</code>
     */
    public Builder setQuoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      quote_ = value;
      onChanged();
      return this;
    }

    private Object null_ = "";
    /**
     * <code>string null = 4;</code>
     */
    public String getNull() {
      Object ref = null_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        null_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string null = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNullBytes() {
      Object ref = null_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        null_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string null = 4;</code>
     */
    public Builder setNull(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      null_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string null = 4;</code>
     */
    public Builder clearNull() {
      
      null_ = getDefaultInstance().getNull();
      onChanged();
      return this;
    }
    /**
     * <code>string null = 4;</code>
     */
    public Builder setNullBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      null_ = value;
      onChanged();
      return this;
    }

    private Object escape_ = "";
    /**
     * <code>string escape = 5;</code>
     */
    public String getEscape() {
      Object ref = escape_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        escape_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string escape = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEscapeBytes() {
      Object ref = escape_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        escape_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string escape = 5;</code>
     */
    public Builder setEscape(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      escape_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string escape = 5;</code>
     */
    public Builder clearEscape() {
      
      escape_ = getDefaultInstance().getEscape();
      onChanged();
      return this;
    }
    /**
     * <code>string escape = 5;</code>
     */
    public Builder setEscapeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      escape_ = value;
      onChanged();
      return this;
    }

    private Object forceNotNull_ = "";
    /**
     * <code>string force_not_null = 6;</code>
     */
    public String getForceNotNull() {
      Object ref = forceNotNull_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        forceNotNull_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string force_not_null = 6;</code>
     */
    public com.google.protobuf.ByteString
        getForceNotNullBytes() {
      Object ref = forceNotNull_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        forceNotNull_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string force_not_null = 6;</code>
     */
    public Builder setForceNotNull(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      forceNotNull_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string force_not_null = 6;</code>
     */
    public Builder clearForceNotNull() {
      
      forceNotNull_ = getDefaultInstance().getForceNotNull();
      onChanged();
      return this;
    }
    /**
     * <code>string force_not_null = 6;</code>
     */
    public Builder setForceNotNullBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      forceNotNull_ = value;
      onChanged();
      return this;
    }

    private Object newline_ = "";
    /**
     * <code>string newline = 7;</code>
     */
    public String getNewline() {
      Object ref = newline_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        newline_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string newline = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNewlineBytes() {
      Object ref = newline_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        newline_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string newline = 7;</code>
     */
    public Builder setNewline(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newline_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string newline = 7;</code>
     */
    public Builder clearNewline() {
      
      newline_ = getDefaultInstance().getNewline();
      onChanged();
      return this;
    }
    /**
     * <code>string newline = 7;</code>
     */
    public Builder setNewlineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newline_ = value;
      onChanged();
      return this;
    }

    private boolean fillMissingFields_ ;
    /**
     * <code>bool fill_missing_fields = 8;</code>
     */
    public boolean getFillMissingFields() {
      return fillMissingFields_;
    }
    /**
     * <code>bool fill_missing_fields = 8;</code>
     */
    public Builder setFillMissingFields(boolean value) {
      
      fillMissingFields_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool fill_missing_fields = 8;</code>
     */
    public Builder clearFillMissingFields() {
      
      fillMissingFields_ = false;
      onChanged();
      return this;
    }

    private boolean header_ ;
    /**
     * <code>bool header = 9;</code>
     */
    public boolean getHeader() {
      return header_;
    }
    /**
     * <code>bool header = 9;</code>
     */
    public Builder setHeader(boolean value) {
      
      header_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool header = 9;</code>
     */
    public Builder clearHeader() {
      
      header_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:api.FormatCSV)
  }

  // @@protoc_insertion_point(class_scope:api.FormatCSV)
  private static final FormatCSV DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FormatCSV();
  }

  public static FormatCSV getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FormatCSV>
      PARSER = new com.google.protobuf.AbstractParser<FormatCSV>() {
    public FormatCSV parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FormatCSV(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FormatCSV> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FormatCSV> getParserForType() {
    return PARSER;
  }

  public FormatCSV getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

