// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public final class GpssOuterClass {
  private GpssOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_InsertOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_InsertOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_UpdateOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_UpdateOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_MergeOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_MergeOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_OpenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_OpenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_DBValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_DBValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_RowData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_RowData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_TransferStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_TransferStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_CloseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_CloseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ListSchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ListSchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Schema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Schema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Schemas_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Schemas_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ListTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ListTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_DescribeTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_DescribeTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_TableInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_TableInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Tables_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Tables_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Columns_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Columns_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ColumnInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ColumnInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SourceDataFormat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SourceDataFormat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_FormatAvro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_FormatAvro_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_FormatBinary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_FormatBinary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_FormatCSV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_FormatCSV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_FormatDelimited_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_FormatDelimited_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_FormatJSON_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_FormatJSON_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_FormatCustom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_FormatCustom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_IntermediateColumn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_IntermediateColumn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ngpss.proto\022\003api\032\033google/protobuf/empty" +
      ".proto\032\034google/protobuf/struct.proto\032\037go" +
      "ogle/protobuf/timestamp.proto\"\204\001\n\016Connec" +
      "tRequest\022\014\n\004Host\030\001 \001(\t\022\014\n\004Port\030\002 \001(\005\022\020\n\010" +
      "Username\030\003 \001(\t\022\020\n\010Password\030\004 \001(\t\022\n\n\002DB\030\005" +
      " \001(\t\022\016\n\006UseSSL\030\006 \001(\010\022\026\n\016SessionTimeout\030\007" +
      " \001(\005\"\025\n\007Session\022\n\n\002ID\030\001 \001(\t\"s\n\014InsertOpt" +
      "ion\022\025\n\rInsertColumns\030\001 \003(\t\022\025\n\rTruncateTa" +
      "ble\030\002 \001(\010\022\027\n\017ErrorLimitCount\030\004 \001(\003\022\034\n\024Er" +
      "rorLimitPercentage\030\005 \001(\005\"\205\001\n\014UpdateOptio",
      "n\022\024\n\014MatchColumns\030\001 \003(\t\022\025\n\rUpdateColumns" +
      "\030\002 \003(\t\022\021\n\tCondition\030\003 \001(\t\022\027\n\017ErrorLimitC" +
      "ount\030\004 \001(\003\022\034\n\024ErrorLimitPercentage\030\005 \001(\005" +
      "\"\233\001\n\013MergeOption\022\025\n\rInsertColumns\030\001 \003(\t\022" +
      "\024\n\014MatchColumns\030\002 \003(\t\022\025\n\rUpdateColumns\030\003" +
      " \003(\t\022\021\n\tCondition\030\004 \001(\t\022\027\n\017ErrorLimitCou" +
      "nt\030\005 \001(\003\022\034\n\024ErrorLimitPercentage\030\006 \001(\005\"\220" +
      "\004\n\013OpenRequest\022\035\n\007Session\030\001 \001(\0132\014.api.Se" +
      "ssion\022\022\n\nSchemaName\030\002 \001(\t\022\021\n\tTableName\030\003" +
      " \001(\t\022\016\n\006PreSQL\030\004 \001(\t\022\017\n\007PostSQL\030\005 \001(\t\022\017\n",
      "\007Timeout\030\006 \001(\005\022\020\n\010Encoding\030\007 \001(\t\022\025\n\rStag" +
      "ingSchema\030\010 \001(\t\022\035\n\004avro\030\t \001(\0132\017.api.Form" +
      "atAvro\022!\n\006binary\030\n \001(\0132\021.api.FormatBinar" +
      "y\022\033\n\003csv\030\013 \001(\0132\016.api.FormatCSV\022\'\n\tdelimi" +
      "ted\030\014 \001(\0132\024.api.FormatDelimited\022\035\n\004json\030" +
      "\r \001(\0132\017.api.FormatJSON\022!\n\006custom\030\016 \001(\0132\021" +
      ".api.FormatCustom\022\r\n\005proto\030\017 \001(\t\022)\n\014Inse" +
      "rtOption\030d \001(\0132\021.api.InsertOptionH\000\022)\n\014U" +
      "pdateOption\030e \001(\0132\021.api.UpdateOptionH\000\022\'" +
      "\n\013MergeOption\030f \001(\0132\020.api.MergeOptionH\000B",
      "\010\n\006Option\"\231\002\n\007DBValue\022\024\n\nInt32Value\030\001 \001(" +
      "\005H\000\022\024\n\nInt64Value\030\002 \001(\003H\000\022\026\n\014Float32Valu" +
      "e\030\005 \001(\002H\000\022\026\n\014Float64Value\030\006 \001(\001H\000\022\025\n\013Str" +
      "ingValue\030\007 \001(\tH\000\022\024\n\nBytesValue\030\010 \001(\014H\000\0224" +
      "\n\016TimeStampValue\030\n \001(\0132\032.google.protobuf" +
      ".TimestampH\000\022/\n\tNullValue\030\013 \001(\0162\032.google" +
      ".protobuf.NullValueH\000\022\024\n\nOtherValue\030\014 \001(" +
      "\tH\000B\010\n\006DBType\"$\n\003Row\022\035\n\007Columns\030\001 \003(\0132\014." +
      "api.DBValue\"\027\n\007RowData\022\014\n\004Data\030\001 \001(\014\"I\n\014" +
      "WriteRequest\022\035\n\007Session\030\001 \001(\0132\014.api.Sess",
      "ion\022\032\n\004Rows\030\002 \003(\0132\014.api.RowData\"L\n\rTrans" +
      "ferStats\022\024\n\014SuccessCount\030\001 \001(\003\022\022\n\nErrorC" +
      "ount\030\002 \001(\003\022\021\n\tErrorRows\030\003 \003(\t\"R\n\014CloseRe" +
      "quest\022\035\n\007session\030\001 \001(\0132\014.api.Session\022\024\n\014" +
      "MaxErrorRows\030\002 \001(\005\022\r\n\005Abort\030\003 \001(\010\"2\n\021Lis" +
      "tSchemaRequest\022\035\n\007Session\030\001 \001(\0132\014.api.Se" +
      "ssion\"%\n\006Schema\022\014\n\004Name\030\001 \001(\t\022\r\n\005Owner\030\002" +
      " \001(\t\"\'\n\007Schemas\022\034\n\007Schemas\030\001 \003(\0132\013.api.S" +
      "chema\"A\n\020ListTableRequest\022\035\n\007Session\030\001 \001" +
      "(\0132\014.api.Session\022\016\n\006Schema\030\002 \001(\t\"\\\n\024Desc",
      "ribeTableRequest\022\035\n\007Session\030\001 \001(\0132\014.api." +
      "Session\022\022\n\nSchemaName\030\002 \001(\t\022\021\n\tTableName" +
      "\030\003 \001(\t\":\n\tTableInfo\022\014\n\004Name\030\001 \001(\t\022\037\n\004Typ" +
      "e\030\002 \001(\0162\021.api.RelationType\"(\n\006Tables\022\036\n\006" +
      "Tables\030\001 \003(\0132\016.api.TableInfo\"+\n\007Columns\022" +
      " \n\007Columns\030\001 \003(\0132\017.api.ColumnInfo\"\267\001\n\nCo" +
      "lumnInfo\022\014\n\004Name\030\001 \001(\t\022\024\n\014DatabaseType\030\002" +
      " \001(\t\022\021\n\tHasLength\030\003 \001(\010\022\016\n\006Length\030\004 \001(\003\022" +
      "\031\n\021HasPrecisionScale\030\005 \001(\010\022\021\n\tPrecision\030" +
      "\006 \001(\003\022\r\n\005Scale\030\007 \001(\003\022\023\n\013HasNullable\030\010 \001(",
      "\010\022\020\n\010Nullable\030\t \001(\010\"\204\002\n\020SourceDataFormat" +
      "\022\037\n\004avro\030\001 \001(\0132\017.api.FormatAvroH\000\022#\n\006bin" +
      "ary\030\002 \001(\0132\021.api.FormatBinaryH\000\022\035\n\003csv\030\003 " +
      "\001(\0132\016.api.FormatCSVH\000\022)\n\tdelimited\030\004 \001(\013" +
      "2\024.api.FormatDelimitedH\000\022\037\n\004json\030\005 \001(\0132\017" +
      ".api.FormatJSONH\000\022#\n\006custom\030\006 \001(\0132\021.api." +
      "FormatCustomH\000\022\022\n\010protobuf\030\007 \001(\tH\000B\006\n\004un" +
      "it\"\210\002\n\nFormatAvro\022\032\n\022source_column_name\030" +
      "\001 \001(\t\022\022\n\nschema_url\030\002 \001(\t\022\027\n\017bytes_to_ba" +
      "se64\030\003 \001(\010\022 \n\030ignore_deserialize_error\030\004",
      " \001(\010\022\033\n\023schema_path_on_gpdb\030\005 \001(\t\022\031\n\021sch" +
      "ema_ca_on_gpdb\030\006 \001(\t\022\033\n\023schema_cert_on_g" +
      "pdb\030\007 \001(\t\022\032\n\022schema_key_on_gpdb\030\010 \001(\t\022\036\n" +
      "\026schema_min_tls_version\030\t \001(\t\"*\n\014FormatB" +
      "inary\022\032\n\022source_column_name\030\001 \001(\t\"\313\001\n\tFo" +
      "rmatCSV\022(\n\007columns\030\001 \003(\0132\027.api.Intermedi" +
      "ateColumn\022\021\n\tdelimiter\030\002 \001(\t\022\r\n\005quote\030\003 " +
      "\001(\t\022\014\n\004null\030\004 \001(\t\022\016\n\006escape\030\005 \001(\t\022\026\n\016for" +
      "ce_not_null\030\006 \001(\t\022\017\n\007newline\030\007 \001(\t\022\033\n\023fi" +
      "ll_missing_fields\030\010 \001(\010\022\016\n\006header\030\t \001(\010\"",
      "N\n\017FormatDelimited\022(\n\007columns\030\001 \003(\0132\027.ap" +
      "i.IntermediateColumn\022\021\n\tdelimiter\030\002 \001(\t\"" +
      "5\n\nFormatJSON\022\'\n\006column\030\001 \001(\0132\027.api.Inte" +
      "rmediateColumn\"W\n\014FormatCustom\022(\n\007column" +
      "s\030\001 \003(\0132\027.api.IntermediateColumn\022\014\n\004name" +
      "\030\002 \001(\t\022\017\n\007options\030\003 \003(\t\"0\n\022IntermediateC" +
      "olumn\022\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 \001(\t*8\n\tOpe" +
      "ration\022\n\n\006Insert\020\000\022\t\n\005Merge\020\001\022\n\n\006Update\020" +
      "\002\022\010\n\004Read\020\003*U\n\014RelationType\022\t\n\005Table\020\000\022\010" +
      "\n\004View\020\001\022\t\n\005Index\020\002\022\014\n\010Sequence\020\003\022\013\n\007Spe",
      "cial\020\004\022\n\n\005Other\020\377\0012\255\003\n\004Gpss\022.\n\007Connect\022\023" +
      ".api.ConnectRequest\032\014.api.Session\"\000\0224\n\nD" +
      "isconnect\022\014.api.Session\032\026.google.protobu" +
      "f.Empty\"\000\0222\n\004Open\022\020.api.OpenRequest\032\026.go" +
      "ogle.protobuf.Empty\"\000\0224\n\005Write\022\021.api.Wri" +
      "teRequest\032\026.google.protobuf.Empty\"\000\0220\n\005C" +
      "lose\022\021.api.CloseRequest\032\022.api.TransferSt" +
      "ats\"\000\0224\n\nListSchema\022\026.api.ListSchemaRequ" +
      "est\032\014.api.Schemas\"\000\0221\n\tListTable\022\025.api.L" +
      "istTableRequest\032\013.api.Tables\"\000\022:\n\rDescri",
      "beTable\022\031.api.DescribeTableRequest\032\014.api" +
      ".Columns\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_api_ConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_ConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ConnectRequest_descriptor,
        new String[] { "Host", "Port", "Username", "Password", "DB", "UseSSL", "SessionTimeout", });
    internal_static_api_Session_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Session_descriptor,
        new String[] { "ID", });
    internal_static_api_InsertOption_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_InsertOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_InsertOption_descriptor,
        new String[] { "InsertColumns", "TruncateTable", "ErrorLimitCount", "ErrorLimitPercentage", });
    internal_static_api_UpdateOption_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_UpdateOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_UpdateOption_descriptor,
        new String[] { "MatchColumns", "UpdateColumns", "Condition", "ErrorLimitCount", "ErrorLimitPercentage", });
    internal_static_api_MergeOption_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_MergeOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_MergeOption_descriptor,
        new String[] { "InsertColumns", "MatchColumns", "UpdateColumns", "Condition", "ErrorLimitCount", "ErrorLimitPercentage", });
    internal_static_api_OpenRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_OpenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_OpenRequest_descriptor,
        new String[] { "Session", "SchemaName", "TableName", "PreSQL", "PostSQL", "Timeout", "Encoding", "StagingSchema", "Avro", "Binary", "Csv", "Delimited", "Json", "Custom", "Proto", "InsertOption", "UpdateOption", "MergeOption", "Option", });
    internal_static_api_DBValue_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_api_DBValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_DBValue_descriptor,
        new String[] { "Int32Value", "Int64Value", "Float32Value", "Float64Value", "StringValue", "BytesValue", "TimeStampValue", "NullValue", "OtherValue", "DBType", });
    internal_static_api_Row_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_api_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Row_descriptor,
        new String[] { "Columns", });
    internal_static_api_RowData_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_api_RowData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_RowData_descriptor,
        new String[] { "Data", });
    internal_static_api_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_api_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_WriteRequest_descriptor,
        new String[] { "Session", "Rows", });
    internal_static_api_TransferStats_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_api_TransferStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_TransferStats_descriptor,
        new String[] { "SuccessCount", "ErrorCount", "ErrorRows", });
    internal_static_api_CloseRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_api_CloseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_CloseRequest_descriptor,
        new String[] { "Session", "MaxErrorRows", "Abort", });
    internal_static_api_ListSchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_api_ListSchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ListSchemaRequest_descriptor,
        new String[] { "Session", });
    internal_static_api_Schema_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_api_Schema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Schema_descriptor,
        new String[] { "Name", "Owner", });
    internal_static_api_Schemas_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_api_Schemas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Schemas_descriptor,
        new String[] { "Schemas", });
    internal_static_api_ListTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_api_ListTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ListTableRequest_descriptor,
        new String[] { "Session", "Schema", });
    internal_static_api_DescribeTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_api_DescribeTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_DescribeTableRequest_descriptor,
        new String[] { "Session", "SchemaName", "TableName", });
    internal_static_api_TableInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_api_TableInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_TableInfo_descriptor,
        new String[] { "Name", "Type", });
    internal_static_api_Tables_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_api_Tables_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Tables_descriptor,
        new String[] { "Tables", });
    internal_static_api_Columns_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_api_Columns_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Columns_descriptor,
        new String[] { "Columns", });
    internal_static_api_ColumnInfo_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_api_ColumnInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ColumnInfo_descriptor,
        new String[] { "Name", "DatabaseType", "HasLength", "Length", "HasPrecisionScale", "Precision", "Scale", "HasNullable", "Nullable", });
    internal_static_api_SourceDataFormat_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_api_SourceDataFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SourceDataFormat_descriptor,
        new String[] { "Avro", "Binary", "Csv", "Delimited", "Json", "Custom", "Protobuf", "Unit", });
    internal_static_api_FormatAvro_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_api_FormatAvro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_FormatAvro_descriptor,
        new String[] { "SourceColumnName", "SchemaUrl", "BytesToBase64", "IgnoreDeserializeError", "SchemaPathOnGpdb", "SchemaCaOnGpdb", "SchemaCertOnGpdb", "SchemaKeyOnGpdb", "SchemaMinTlsVersion", });
    internal_static_api_FormatBinary_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_api_FormatBinary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_FormatBinary_descriptor,
        new String[] { "SourceColumnName", });
    internal_static_api_FormatCSV_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_api_FormatCSV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_FormatCSV_descriptor,
        new String[] { "Columns", "Delimiter", "Quote", "Null", "Escape", "ForceNotNull", "Newline", "FillMissingFields", "Header", });
    internal_static_api_FormatDelimited_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_api_FormatDelimited_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_FormatDelimited_descriptor,
        new String[] { "Columns", "Delimiter", });
    internal_static_api_FormatJSON_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_api_FormatJSON_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_FormatJSON_descriptor,
        new String[] { "Column", });
    internal_static_api_FormatCustom_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_api_FormatCustom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_FormatCustom_descriptor,
        new String[] { "Columns", "Name", "Options", });
    internal_static_api_IntermediateColumn_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_api_IntermediateColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_IntermediateColumn_descriptor,
        new String[] { "Name", "Type", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
