// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface InsertOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.InsertOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  java.util.List<String>
      getInsertColumnsList();
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  int getInsertColumnsCount();
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  String getInsertColumns(int index);
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  com.google.protobuf.ByteString
      getInsertColumnsBytes(int index);

  /**
   * <pre>
   * Truncate table before loading?
   * </pre>
   *
   * <code>bool TruncateTable = 2;</code>
   */
  boolean getTruncateTable();

  /**
   * <pre>
   * Error limit count; used by external table
   * </pre>
   *
   * <code>int64 ErrorLimitCount = 4;</code>
   */
  long getErrorLimitCount();

  /**
   * <pre>
   * Error limit percentage; used by external table
   * </pre>
   *
   * <code>int32 ErrorLimitPercentage = 5;</code>
   */
  int getErrorLimitPercentage();
}
