// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

/**
 * <pre>
 * Required parameters of the Insert operation
 * </pre>
 *
 * Protobuf type {@code InsertOption}
 */
public  final class InsertOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.InsertOption)
    InsertOptionOrBuilder {
  // Use InsertOption.newBuilder() to construct.
  private InsertOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InsertOption() {
    insertColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    truncateTable_ = false;
    errorLimitCount_ = 0L;
    errorLimitPercentage_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private InsertOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              insertColumns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            insertColumns_.add(s);
            break;
          }
          case 16: {

            truncateTable_ = input.readBool();
            break;
          }
          case 32: {

            errorLimitCount_ = input.readInt64();
            break;
          }
          case 40: {

            errorLimitPercentage_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        insertColumns_ = insertColumns_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GpssOuterClass.internal_static_api_InsertOption_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GpssOuterClass.internal_static_api_InsertOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InsertOption.class, InsertOption.Builder.class);
  }

  private int bitField0_;
  public static final int INSERTCOLUMNS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList insertColumns_;
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getInsertColumnsList() {
    return insertColumns_;
  }
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  public int getInsertColumnsCount() {
    return insertColumns_.size();
  }
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  public String getInsertColumns(int index) {
    return insertColumns_.get(index);
  }
  /**
   * <pre>
   * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
   * </pre>
   *
   * <code>repeated string InsertColumns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getInsertColumnsBytes(int index) {
    return insertColumns_.getByteString(index);
  }

  public static final int TRUNCATETABLE_FIELD_NUMBER = 2;
  private boolean truncateTable_;
  /**
   * <pre>
   * Truncate table before loading?
   * </pre>
   *
   * <code>bool TruncateTable = 2;</code>
   */
  public boolean getTruncateTable() {
    return truncateTable_;
  }

  public static final int ERRORLIMITCOUNT_FIELD_NUMBER = 4;
  private long errorLimitCount_;
  /**
   * <pre>
   * Error limit count; used by external table
   * </pre>
   *
   * <code>int64 ErrorLimitCount = 4;</code>
   */
  public long getErrorLimitCount() {
    return errorLimitCount_;
  }

  public static final int ERRORLIMITPERCENTAGE_FIELD_NUMBER = 5;
  private int errorLimitPercentage_;
  /**
   * <pre>
   * Error limit percentage; used by external table
   * </pre>
   *
   * <code>int32 ErrorLimitPercentage = 5;</code>
   */
  public int getErrorLimitPercentage() {
    return errorLimitPercentage_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < insertColumns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, insertColumns_.getRaw(i));
    }
    if (truncateTable_ != false) {
      output.writeBool(2, truncateTable_);
    }
    if (errorLimitCount_ != 0L) {
      output.writeInt64(4, errorLimitCount_);
    }
    if (errorLimitPercentage_ != 0) {
      output.writeInt32(5, errorLimitPercentage_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < insertColumns_.size(); i++) {
        dataSize += computeStringSizeNoTag(insertColumns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInsertColumnsList().size();
    }
    if (truncateTable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, truncateTable_);
    }
    if (errorLimitCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, errorLimitCount_);
    }
    if (errorLimitPercentage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, errorLimitPercentage_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InsertOption)) {
      return super.equals(obj);
    }
    InsertOption other =  (InsertOption) obj;

    boolean result = true;
    result = result && getInsertColumnsList()
        .equals(other.getInsertColumnsList());
    result = result && (getTruncateTable()
        == other.getTruncateTable());
    result = result && (getErrorLimitCount()
        == other.getErrorLimitCount());
    result = result && (getErrorLimitPercentage()
        == other.getErrorLimitPercentage());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInsertColumnsCount() > 0) {
      hash = (37 * hash) + INSERTCOLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getInsertColumnsList().hashCode();
    }
    hash = (37 * hash) + TRUNCATETABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTruncateTable());
    hash = (37 * hash) + ERRORLIMITCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getErrorLimitCount());
    hash = (37 * hash) + ERRORLIMITPERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorLimitPercentage();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InsertOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InsertOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InsertOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InsertOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InsertOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InsertOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InsertOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InsertOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InsertOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InsertOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InsertOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InsertOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder (InsertOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Required parameters of the Insert operation
   * </pre>
   *
   * Protobuf type {@code InsertOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.InsertOption)
      InsertOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GpssOuterClass.internal_static_api_InsertOption_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GpssOuterClass.internal_static_api_InsertOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InsertOption.class, InsertOption.Builder.class);
    }

    // Construct using InsertOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      insertColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      truncateTable_ = false;

      errorLimitCount_ = 0L;

      errorLimitPercentage_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GpssOuterClass.internal_static_api_InsertOption_descriptor;
    }

    public InsertOption getDefaultInstanceForType() {
      return InsertOption.getDefaultInstance();
    }

    public InsertOption build() {
      InsertOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public InsertOption buildPartial() {
      InsertOption result = new InsertOption(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        insertColumns_ = insertColumns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.insertColumns_ = insertColumns_;
      result.truncateTable_ = truncateTable_;
      result.errorLimitCount_ = errorLimitCount_;
      result.errorLimitPercentage_ = errorLimitPercentage_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InsertOption) {
        return mergeFrom( (InsertOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom (InsertOption other) {
      if (other == InsertOption.getDefaultInstance()) return this;
      if (!other.insertColumns_.isEmpty()) {
        if (insertColumns_.isEmpty()) {
          insertColumns_ = other.insertColumns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureInsertColumnsIsMutable();
          insertColumns_.addAll(other.insertColumns_);
        }
        onChanged();
      }
      if (other.getTruncateTable() != false) {
        setTruncateTable(other.getTruncateTable());
      }
      if (other.getErrorLimitCount() != 0L) {
        setErrorLimitCount(other.getErrorLimitCount());
      }
      if (other.getErrorLimitPercentage() != 0) {
        setErrorLimitPercentage(other.getErrorLimitPercentage());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      InsertOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =  (InsertOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList insertColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInsertColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        insertColumns_ = new com.google.protobuf.LazyStringArrayList(insertColumns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInsertColumnsList() {
      return insertColumns_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public int getInsertColumnsCount() {
      return insertColumns_.size();
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public String getInsertColumns(int index) {
      return insertColumns_.get(index);
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInsertColumnsBytes(int index) {
      return insertColumns_.getByteString(index);
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public Builder setInsertColumns(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInsertColumnsIsMutable();
      insertColumns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public Builder addInsertColumns(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInsertColumnsIsMutable();
      insertColumns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public Builder addAllInsertColumns(
        Iterable<String> values) {
      ensureInsertColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, insertColumns_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public Builder clearInsertColumns() {
      insertColumns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Names of the target table columns the insert operation should update; used in 'INSERT INTO', useful for partial loading
     * </pre>
     *
     * <code>repeated string InsertColumns = 1;</code>
     */
    public Builder addInsertColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureInsertColumnsIsMutable();
      insertColumns_.add(value);
      onChanged();
      return this;
    }

    private boolean truncateTable_ ;
    /**
     * <pre>
     * Truncate table before loading?
     * </pre>
     *
     * <code>bool TruncateTable = 2;</code>
     */
    public boolean getTruncateTable() {
      return truncateTable_;
    }
    /**
     * <pre>
     * Truncate table before loading?
     * </pre>
     *
     * <code>bool TruncateTable = 2;</code>
     */
    public Builder setTruncateTable(boolean value) {
      
      truncateTable_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Truncate table before loading?
     * </pre>
     *
     * <code>bool TruncateTable = 2;</code>
     */
    public Builder clearTruncateTable() {
      
      truncateTable_ = false;
      onChanged();
      return this;
    }

    private long errorLimitCount_ ;
    /**
     * <pre>
     * Error limit count; used by external table
     * </pre>
     *
     * <code>int64 ErrorLimitCount = 4;</code>
     */
    public long getErrorLimitCount() {
      return errorLimitCount_;
    }
    /**
     * <pre>
     * Error limit count; used by external table
     * </pre>
     *
     * <code>int64 ErrorLimitCount = 4;</code>
     */
    public Builder setErrorLimitCount(long value) {
      
      errorLimitCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error limit count; used by external table
     * </pre>
     *
     * <code>int64 ErrorLimitCount = 4;</code>
     */
    public Builder clearErrorLimitCount() {
      
      errorLimitCount_ = 0L;
      onChanged();
      return this;
    }

    private int errorLimitPercentage_ ;
    /**
     * <pre>
     * Error limit percentage; used by external table
     * </pre>
     *
     * <code>int32 ErrorLimitPercentage = 5;</code>
     */
    public int getErrorLimitPercentage() {
      return errorLimitPercentage_;
    }
    /**
     * <pre>
     * Error limit percentage; used by external table
     * </pre>
     *
     * <code>int32 ErrorLimitPercentage = 5;</code>
     */
    public Builder setErrorLimitPercentage(int value) {
      
      errorLimitPercentage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error limit percentage; used by external table
     * </pre>
     *
     * <code>int32 ErrorLimitPercentage = 5;</code>
     */
    public Builder clearErrorLimitPercentage() {
      
      errorLimitPercentage_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:api.InsertOption)
  }

  // @@protoc_insertion_point(class_scope:api.InsertOption)
  private static final InsertOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InsertOption();
  }

  public static InsertOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InsertOption>
      PARSER = new com.google.protobuf.AbstractParser<InsertOption>() {
    public InsertOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InsertOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InsertOption> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InsertOption> getParserForType() {
    return PARSER;
  }

  public InsertOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

