// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

/**
 * Protobuf enum {@code RelationType}
 */
public enum RelationType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Table = 0;</code>
   */
  Table(0),
  /**
   * <code>View = 1;</code>
   */
  View(1),
  /**
   * <code>Index = 2;</code>
   */
  Index(2),
  /**
   * <code>Sequence = 3;</code>
   */
  Sequence(3),
  /**
   * <code>Special = 4;</code>
   */
  Special(4),
  /**
   * <code>Other = 255;</code>
   */
  Other(255),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Table = 0;</code>
   */
  public static final int Table_VALUE = 0;
  /**
   * <code>View = 1;</code>
   */
  public static final int View_VALUE = 1;
  /**
   * <code>Index = 2;</code>
   */
  public static final int Index_VALUE = 2;
  /**
   * <code>Sequence = 3;</code>
   */
  public static final int Sequence_VALUE = 3;
  /**
   * <code>Special = 4;</code>
   */
  public static final int Special_VALUE = 4;
  /**
   * <code>Other = 255;</code>
   */
  public static final int Other_VALUE = 255;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static RelationType valueOf(int value) {
    return forNumber(value);
  }

  public static RelationType forNumber(int value) {
    switch (value) {
      case 0: return Table;
      case 1: return View;
      case 2: return Index;
      case 3: return Sequence;
      case 4: return Special;
      case 255: return Other;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RelationType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RelationType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RelationType>() {
          public RelationType findValueByNumber(int number) {
            return RelationType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return GpssOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final RelationType[] VALUES = values();

  public static RelationType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RelationType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.RelationType)
}

