// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface SchemasOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Schemas)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  java.util.List<Schema> 
      getSchemasList();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  Schema getSchemas(int index);
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  int getSchemasCount();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  java.util.List<? extends SchemaOrBuilder> 
      getSchemasOrBuilderList();
  /**
   * <code>repeated .api.Schema Schemas = 1;</code>
   */
  SchemaOrBuilder getSchemasOrBuilder(
      int index);
}
