// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

/**
 * <pre>
 * The format of the source data.
 * If there is an intermediate column inside Format,
 * then the source data will be transformed to the intermediate column.
 * If there is no source_column_name in Format,
 * then the column name will be the Target table column name,
 * and the source column data type will be matched with Target column type.
 * </pre>
 *
 * Protobuf type {@code SourceDataFormat}
 */
public  final class SourceDataFormat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.SourceDataFormat)
    SourceDataFormatOrBuilder {
  // Use SourceDataFormat.newBuilder() to construct.
  private SourceDataFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SourceDataFormat() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SourceDataFormat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            FormatAvro.Builder subBuilder = null;
            if (unitCase_ == 1) {
              subBuilder = ( (FormatAvro) unit_).toBuilder();
            }
            unit_ =
                input.readMessage (FormatAvro.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom( (FormatAvro) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 1;
            break;
          }
          case 18: {
            FormatBinary.Builder subBuilder = null;
            if (unitCase_ == 2) {
              subBuilder = ( (FormatBinary) unit_).toBuilder();
            }
            unit_ =
                input.readMessage (FormatBinary.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom( (FormatBinary) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 2;
            break;
          }
          case 26: {
            FormatCSV.Builder subBuilder = null;
            if (unitCase_ == 3) {
              subBuilder = ( (FormatCSV) unit_).toBuilder();
            }
            unit_ =
                input.readMessage (FormatCSV.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom( (FormatCSV) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 3;
            break;
          }
          case 34: {
            FormatDelimited.Builder subBuilder = null;
            if (unitCase_ == 4) {
              subBuilder = ( (FormatDelimited) unit_).toBuilder();
            }
            unit_ =
                input.readMessage (FormatDelimited.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom( (FormatDelimited) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 4;
            break;
          }
          case 42: {
            FormatJSON.Builder subBuilder = null;
            if (unitCase_ == 5) {
              subBuilder = ( (FormatJSON) unit_).toBuilder();
            }
            unit_ =
                input.readMessage (FormatJSON.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom( (FormatJSON) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 5;
            break;
          }
          case 50: {
            FormatCustom.Builder subBuilder = null;
            if (unitCase_ == 6) {
              subBuilder = ( (FormatCustom) unit_).toBuilder();
            }
            unit_ =
                input.readMessage (FormatCustom.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom( (FormatCustom) unit_);
              unit_ = subBuilder.buildPartial();
            }
            unitCase_ = 6;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();
            unitCase_ = 7;
            unit_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GpssOuterClass.internal_static_api_SourceDataFormat_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GpssOuterClass.internal_static_api_SourceDataFormat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SourceDataFormat.class, SourceDataFormat.Builder.class);
  }

  private int unitCase_ = 0;
  private Object unit_;
  public enum UnitCase
      implements com.google.protobuf.Internal.EnumLite {
    AVRO(1),
    BINARY(2),
    CSV(3),
    DELIMITED(4),
    JSON(5),
    CUSTOM(6),
    PROTOBUF(7),
    UNIT_NOT_SET(0);
    private final int value;
    private UnitCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static UnitCase valueOf(int value) {
      return forNumber(value);
    }

    public static UnitCase forNumber(int value) {
      switch (value) {
        case 1: return AVRO;
        case 2: return BINARY;
        case 3: return CSV;
        case 4: return DELIMITED;
        case 5: return JSON;
        case 6: return CUSTOM;
        case 7: return PROTOBUF;
        case 0: return UNIT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UnitCase
  getUnitCase() {
    return UnitCase.forNumber(
        unitCase_);
  }

  public static final int AVRO_FIELD_NUMBER = 1;
  /**
   * <code>.api.FormatAvro avro = 1;</code>
   */
  public FormatAvro getAvro() {
    if (unitCase_ == 1) {
       return  (FormatAvro) unit_;
    }
    return FormatAvro.getDefaultInstance();
  }
  /**
   * <code>.api.FormatAvro avro = 1;</code>
   */
  public FormatAvroOrBuilder getAvroOrBuilder() {
    if (unitCase_ == 1) {
       return  (FormatAvro) unit_;
    }
    return FormatAvro.getDefaultInstance();
  }

  public static final int BINARY_FIELD_NUMBER = 2;
  /**
   * <code>.api.FormatBinary binary = 2;</code>
   */
  public FormatBinary getBinary() {
    if (unitCase_ == 2) {
       return  (FormatBinary) unit_;
    }
    return FormatBinary.getDefaultInstance();
  }
  /**
   * <code>.api.FormatBinary binary = 2;</code>
   */
  public FormatBinaryOrBuilder getBinaryOrBuilder() {
    if (unitCase_ == 2) {
       return  (FormatBinary) unit_;
    }
    return FormatBinary.getDefaultInstance();
  }

  public static final int CSV_FIELD_NUMBER = 3;
  /**
   * <code>.api.FormatCSV csv = 3;</code>
   */
  public FormatCSV getCsv() {
    if (unitCase_ == 3) {
       return  (FormatCSV) unit_;
    }
    return FormatCSV.getDefaultInstance();
  }
  /**
   * <code>.api.FormatCSV csv = 3;</code>
   */
  public FormatCSVOrBuilder getCsvOrBuilder() {
    if (unitCase_ == 3) {
       return  (FormatCSV) unit_;
    }
    return FormatCSV.getDefaultInstance();
  }

  public static final int DELIMITED_FIELD_NUMBER = 4;
  /**
   * <code>.api.FormatDelimited delimited = 4;</code>
   */
  public FormatDelimited getDelimited() {
    if (unitCase_ == 4) {
       return  (FormatDelimited) unit_;
    }
    return FormatDelimited.getDefaultInstance();
  }
  /**
   * <code>.api.FormatDelimited delimited = 4;</code>
   */
  public FormatDelimitedOrBuilder getDelimitedOrBuilder() {
    if (unitCase_ == 4) {
       return  (FormatDelimited) unit_;
    }
    return FormatDelimited.getDefaultInstance();
  }

  public static final int JSON_FIELD_NUMBER = 5;
  /**
   * <code>.api.FormatJSON json = 5;</code>
   */
  public FormatJSON getJson() {
    if (unitCase_ == 5) {
       return  (FormatJSON) unit_;
    }
    return FormatJSON.getDefaultInstance();
  }
  /**
   * <code>.api.FormatJSON json = 5;</code>
   */
  public FormatJSONOrBuilder getJsonOrBuilder() {
    if (unitCase_ == 5) {
       return  (FormatJSON) unit_;
    }
    return FormatJSON.getDefaultInstance();
  }

  public static final int CUSTOM_FIELD_NUMBER = 6;
  /**
   * <code>.api.FormatCustom custom = 6;</code>
   */
  public FormatCustom getCustom() {
    if (unitCase_ == 6) {
       return  (FormatCustom) unit_;
    }
    return FormatCustom.getDefaultInstance();
  }
  /**
   * <code>.api.FormatCustom custom = 6;</code>
   */
  public FormatCustomOrBuilder getCustomOrBuilder() {
    if (unitCase_ == 6) {
       return  (FormatCustom) unit_;
    }
    return FormatCustom.getDefaultInstance();
  }

  public static final int PROTOBUF_FIELD_NUMBER = 7;
  /**
   * <code>string protobuf = 7;</code>
   */
  public String getProtobuf() {
    Object ref = "";
    if (unitCase_ == 7) {
      ref = unit_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (unitCase_ == 7) {
        unit_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string protobuf = 7;</code>
   */
  public com.google.protobuf.ByteString
      getProtobufBytes() {
    Object ref = "";
    if (unitCase_ == 7) {
      ref = unit_;
    }
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      if (unitCase_ == 7) {
        unit_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unitCase_ == 1) {
      output.writeMessage(1,  (FormatAvro) unit_);
    }
    if (unitCase_ == 2) {
      output.writeMessage(2,  (FormatBinary) unit_);
    }
    if (unitCase_ == 3) {
      output.writeMessage(3,  (FormatCSV) unit_);
    }
    if (unitCase_ == 4) {
      output.writeMessage(4,  (FormatDelimited) unit_);
    }
    if (unitCase_ == 5) {
      output.writeMessage(5,  (FormatJSON) unit_);
    }
    if (unitCase_ == 6) {
      output.writeMessage(6,  (FormatCustom) unit_);
    }
    if (unitCase_ == 7) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, unit_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unitCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1,  (FormatAvro) unit_);
    }
    if (unitCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2,  (FormatBinary) unit_);
    }
    if (unitCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3,  (FormatCSV) unit_);
    }
    if (unitCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4,  (FormatDelimited) unit_);
    }
    if (unitCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5,  (FormatJSON) unit_);
    }
    if (unitCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6,  (FormatCustom) unit_);
    }
    if (unitCase_ == 7) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, unit_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SourceDataFormat)) {
      return super.equals(obj);
    }
    SourceDataFormat other =  (SourceDataFormat) obj;

    boolean result = true;
    result = result && getUnitCase().equals(
        other.getUnitCase());
    if (!result) return false;
    switch (unitCase_) {
      case 1:
        result = result && getAvro()
            .equals(other.getAvro());
        break;
      case 2:
        result = result && getBinary()
            .equals(other.getBinary());
        break;
      case 3:
        result = result && getCsv()
            .equals(other.getCsv());
        break;
      case 4:
        result = result && getDelimited()
            .equals(other.getDelimited());
        break;
      case 5:
        result = result && getJson()
            .equals(other.getJson());
        break;
      case 6:
        result = result && getCustom()
            .equals(other.getCustom());
        break;
      case 7:
        result = result && getProtobuf()
            .equals(other.getProtobuf());
        break;
      case 0:
      default:
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (unitCase_) {
      case 1:
        hash = (37 * hash) + AVRO_FIELD_NUMBER;
        hash = (53 * hash) + getAvro().hashCode();
        break;
      case 2:
        hash = (37 * hash) + BINARY_FIELD_NUMBER;
        hash = (53 * hash) + getBinary().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CSV_FIELD_NUMBER;
        hash = (53 * hash) + getCsv().hashCode();
        break;
      case 4:
        hash = (37 * hash) + DELIMITED_FIELD_NUMBER;
        hash = (53 * hash) + getDelimited().hashCode();
        break;
      case 5:
        hash = (37 * hash) + JSON_FIELD_NUMBER;
        hash = (53 * hash) + getJson().hashCode();
        break;
      case 6:
        hash = (37 * hash) + CUSTOM_FIELD_NUMBER;
        hash = (53 * hash) + getCustom().hashCode();
        break;
      case 7:
        hash = (37 * hash) + PROTOBUF_FIELD_NUMBER;
        hash = (53 * hash) + getProtobuf().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SourceDataFormat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SourceDataFormat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SourceDataFormat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SourceDataFormat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SourceDataFormat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SourceDataFormat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SourceDataFormat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SourceDataFormat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SourceDataFormat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SourceDataFormat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SourceDataFormat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SourceDataFormat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder (SourceDataFormat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The format of the source data.
   * If there is an intermediate column inside Format,
   * then the source data will be transformed to the intermediate column.
   * If there is no source_column_name in Format,
   * then the column name will be the Target table column name,
   * and the source column data type will be matched with Target column type.
   * </pre>
   *
   * Protobuf type {@code SourceDataFormat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.SourceDataFormat)
      SourceDataFormatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GpssOuterClass.internal_static_api_SourceDataFormat_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GpssOuterClass.internal_static_api_SourceDataFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SourceDataFormat.class, SourceDataFormat.Builder.class);
    }

    // Construct using SourceDataFormat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      unitCase_ = 0;
      unit_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GpssOuterClass.internal_static_api_SourceDataFormat_descriptor;
    }

    public SourceDataFormat getDefaultInstanceForType() {
      return SourceDataFormat.getDefaultInstance();
    }

    public SourceDataFormat build() {
      SourceDataFormat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public SourceDataFormat buildPartial() {
      SourceDataFormat result = new SourceDataFormat(this);
      if (unitCase_ == 1) {
        if (avroBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = avroBuilder_.build();
        }
      }
      if (unitCase_ == 2) {
        if (binaryBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = binaryBuilder_.build();
        }
      }
      if (unitCase_ == 3) {
        if (csvBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = csvBuilder_.build();
        }
      }
      if (unitCase_ == 4) {
        if (delimitedBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = delimitedBuilder_.build();
        }
      }
      if (unitCase_ == 5) {
        if (jsonBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = jsonBuilder_.build();
        }
      }
      if (unitCase_ == 6) {
        if (customBuilder_ == null) {
          result.unit_ = unit_;
        } else {
          result.unit_ = customBuilder_.build();
        }
      }
      if (unitCase_ == 7) {
        result.unit_ = unit_;
      }
      result.unitCase_ = unitCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SourceDataFormat) {
        return mergeFrom( (SourceDataFormat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom (SourceDataFormat other) {
      if (other == SourceDataFormat.getDefaultInstance()) return this;
      switch (other.getUnitCase()) {
        case AVRO: {
          mergeAvro(other.getAvro());
          break;
        }
        case BINARY: {
          mergeBinary(other.getBinary());
          break;
        }
        case CSV: {
          mergeCsv(other.getCsv());
          break;
        }
        case DELIMITED: {
          mergeDelimited(other.getDelimited());
          break;
        }
        case JSON: {
          mergeJson(other.getJson());
          break;
        }
        case CUSTOM: {
          mergeCustom(other.getCustom());
          break;
        }
        case PROTOBUF: {
          unitCase_ = 7;
          unit_ = other.unit_;
          onChanged();
          break;
        }
        case UNIT_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SourceDataFormat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =  (SourceDataFormat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int unitCase_ = 0;
    private Object unit_;
    public UnitCase
        getUnitCase() {
      return UnitCase.forNumber(
          unitCase_);
    }

    public Builder clearUnit() {
      unitCase_ = 0;
      unit_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        FormatAvro, FormatAvro.Builder, FormatAvroOrBuilder> avroBuilder_;
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public FormatAvro getAvro() {
      if (avroBuilder_ == null) {
        if (unitCase_ == 1) {
          return  (FormatAvro) unit_;
        }
        return FormatAvro.getDefaultInstance();
      } else {
        if (unitCase_ == 1) {
          return avroBuilder_.getMessage();
        }
        return FormatAvro.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public Builder setAvro (FormatAvro value) {
      if (avroBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        avroBuilder_.setMessage(value);
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public Builder setAvro(
        FormatAvro.Builder builderForValue) {
      if (avroBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        avroBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public Builder mergeAvro (FormatAvro value) {
      if (avroBuilder_ == null) {
        if (unitCase_ == 1 &&
            unit_ != FormatAvro.getDefaultInstance()) {
          unit_ = FormatAvro.newBuilder( (FormatAvro) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 1) {
          avroBuilder_.mergeFrom(value);
        }
        avroBuilder_.setMessage(value);
      }
      unitCase_ = 1;
      return this;
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public Builder clearAvro() {
      if (avroBuilder_ == null) {
        if (unitCase_ == 1) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 1) {
          unitCase_ = 0;
          unit_ = null;
        }
        avroBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public FormatAvro.Builder getAvroBuilder() {
      return getAvroFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    public FormatAvroOrBuilder getAvroOrBuilder() {
      if ((unitCase_ == 1) && (avroBuilder_ != null)) {
        return avroBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 1) {
          return  (FormatAvro) unit_;
        }
        return FormatAvro.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatAvro avro = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FormatAvro, FormatAvro.Builder, FormatAvroOrBuilder> 
        getAvroFieldBuilder() {
      if (avroBuilder_ == null) {
        if (!(unitCase_ == 1)) {
          unit_ = FormatAvro.getDefaultInstance();
        }
        avroBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FormatAvro, FormatAvro.Builder, FormatAvroOrBuilder>(
                 (FormatAvro) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 1;
      onChanged();;
      return avroBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        FormatBinary, FormatBinary.Builder, FormatBinaryOrBuilder> binaryBuilder_;
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public FormatBinary getBinary() {
      if (binaryBuilder_ == null) {
        if (unitCase_ == 2) {
          return  (FormatBinary) unit_;
        }
        return FormatBinary.getDefaultInstance();
      } else {
        if (unitCase_ == 2) {
          return binaryBuilder_.getMessage();
        }
        return FormatBinary.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public Builder setBinary (FormatBinary value) {
      if (binaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        binaryBuilder_.setMessage(value);
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public Builder setBinary(
        FormatBinary.Builder builderForValue) {
      if (binaryBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        binaryBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public Builder mergeBinary (FormatBinary value) {
      if (binaryBuilder_ == null) {
        if (unitCase_ == 2 &&
            unit_ != FormatBinary.getDefaultInstance()) {
          unit_ = FormatBinary.newBuilder( (FormatBinary) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 2) {
          binaryBuilder_.mergeFrom(value);
        }
        binaryBuilder_.setMessage(value);
      }
      unitCase_ = 2;
      return this;
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public Builder clearBinary() {
      if (binaryBuilder_ == null) {
        if (unitCase_ == 2) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 2) {
          unitCase_ = 0;
          unit_ = null;
        }
        binaryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public FormatBinary.Builder getBinaryBuilder() {
      return getBinaryFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    public FormatBinaryOrBuilder getBinaryOrBuilder() {
      if ((unitCase_ == 2) && (binaryBuilder_ != null)) {
        return binaryBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 2) {
          return  (FormatBinary) unit_;
        }
        return FormatBinary.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatBinary binary = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FormatBinary, FormatBinary.Builder, FormatBinaryOrBuilder> 
        getBinaryFieldBuilder() {
      if (binaryBuilder_ == null) {
        if (!(unitCase_ == 2)) {
          unit_ = FormatBinary.getDefaultInstance();
        }
        binaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FormatBinary, FormatBinary.Builder, FormatBinaryOrBuilder>(
                 (FormatBinary) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 2;
      onChanged();;
      return binaryBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        FormatCSV, FormatCSV.Builder, FormatCSVOrBuilder> csvBuilder_;
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public FormatCSV getCsv() {
      if (csvBuilder_ == null) {
        if (unitCase_ == 3) {
          return  (FormatCSV) unit_;
        }
        return FormatCSV.getDefaultInstance();
      } else {
        if (unitCase_ == 3) {
          return csvBuilder_.getMessage();
        }
        return FormatCSV.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public Builder setCsv (FormatCSV value) {
      if (csvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        csvBuilder_.setMessage(value);
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public Builder setCsv(
        FormatCSV.Builder builderForValue) {
      if (csvBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        csvBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public Builder mergeCsv (FormatCSV value) {
      if (csvBuilder_ == null) {
        if (unitCase_ == 3 &&
            unit_ != FormatCSV.getDefaultInstance()) {
          unit_ = FormatCSV.newBuilder( (FormatCSV) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 3) {
          csvBuilder_.mergeFrom(value);
        }
        csvBuilder_.setMessage(value);
      }
      unitCase_ = 3;
      return this;
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public Builder clearCsv() {
      if (csvBuilder_ == null) {
        if (unitCase_ == 3) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 3) {
          unitCase_ = 0;
          unit_ = null;
        }
        csvBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public FormatCSV.Builder getCsvBuilder() {
      return getCsvFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    public FormatCSVOrBuilder getCsvOrBuilder() {
      if ((unitCase_ == 3) && (csvBuilder_ != null)) {
        return csvBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 3) {
          return  (FormatCSV) unit_;
        }
        return FormatCSV.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatCSV csv = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FormatCSV, FormatCSV.Builder, FormatCSVOrBuilder> 
        getCsvFieldBuilder() {
      if (csvBuilder_ == null) {
        if (!(unitCase_ == 3)) {
          unit_ = FormatCSV.getDefaultInstance();
        }
        csvBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FormatCSV, FormatCSV.Builder, FormatCSVOrBuilder>(
                 (FormatCSV) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 3;
      onChanged();;
      return csvBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        FormatDelimited, FormatDelimited.Builder, FormatDelimitedOrBuilder> delimitedBuilder_;
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public FormatDelimited getDelimited() {
      if (delimitedBuilder_ == null) {
        if (unitCase_ == 4) {
          return  (FormatDelimited) unit_;
        }
        return FormatDelimited.getDefaultInstance();
      } else {
        if (unitCase_ == 4) {
          return delimitedBuilder_.getMessage();
        }
        return FormatDelimited.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public Builder setDelimited (FormatDelimited value) {
      if (delimitedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        delimitedBuilder_.setMessage(value);
      }
      unitCase_ = 4;
      return this;
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public Builder setDelimited(
        FormatDelimited.Builder builderForValue) {
      if (delimitedBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        delimitedBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 4;
      return this;
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public Builder mergeDelimited (FormatDelimited value) {
      if (delimitedBuilder_ == null) {
        if (unitCase_ == 4 &&
            unit_ != FormatDelimited.getDefaultInstance()) {
          unit_ = FormatDelimited.newBuilder( (FormatDelimited) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 4) {
          delimitedBuilder_.mergeFrom(value);
        }
        delimitedBuilder_.setMessage(value);
      }
      unitCase_ = 4;
      return this;
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public Builder clearDelimited() {
      if (delimitedBuilder_ == null) {
        if (unitCase_ == 4) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 4) {
          unitCase_ = 0;
          unit_ = null;
        }
        delimitedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public FormatDelimited.Builder getDelimitedBuilder() {
      return getDelimitedFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    public FormatDelimitedOrBuilder getDelimitedOrBuilder() {
      if ((unitCase_ == 4) && (delimitedBuilder_ != null)) {
        return delimitedBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 4) {
          return  (FormatDelimited) unit_;
        }
        return FormatDelimited.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatDelimited delimited = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FormatDelimited, FormatDelimited.Builder, FormatDelimitedOrBuilder> 
        getDelimitedFieldBuilder() {
      if (delimitedBuilder_ == null) {
        if (!(unitCase_ == 4)) {
          unit_ = FormatDelimited.getDefaultInstance();
        }
        delimitedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FormatDelimited, FormatDelimited.Builder, FormatDelimitedOrBuilder>(
                 (FormatDelimited) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 4;
      onChanged();;
      return delimitedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        FormatJSON, FormatJSON.Builder, FormatJSONOrBuilder> jsonBuilder_;
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public FormatJSON getJson() {
      if (jsonBuilder_ == null) {
        if (unitCase_ == 5) {
          return  (FormatJSON) unit_;
        }
        return FormatJSON.getDefaultInstance();
      } else {
        if (unitCase_ == 5) {
          return jsonBuilder_.getMessage();
        }
        return FormatJSON.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public Builder setJson (FormatJSON value) {
      if (jsonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        jsonBuilder_.setMessage(value);
      }
      unitCase_ = 5;
      return this;
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public Builder setJson(
        FormatJSON.Builder builderForValue) {
      if (jsonBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        jsonBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 5;
      return this;
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public Builder mergeJson (FormatJSON value) {
      if (jsonBuilder_ == null) {
        if (unitCase_ == 5 &&
            unit_ != FormatJSON.getDefaultInstance()) {
          unit_ = FormatJSON.newBuilder( (FormatJSON) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 5) {
          jsonBuilder_.mergeFrom(value);
        }
        jsonBuilder_.setMessage(value);
      }
      unitCase_ = 5;
      return this;
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public Builder clearJson() {
      if (jsonBuilder_ == null) {
        if (unitCase_ == 5) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 5) {
          unitCase_ = 0;
          unit_ = null;
        }
        jsonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public FormatJSON.Builder getJsonBuilder() {
      return getJsonFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    public FormatJSONOrBuilder getJsonOrBuilder() {
      if ((unitCase_ == 5) && (jsonBuilder_ != null)) {
        return jsonBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 5) {
          return  (FormatJSON) unit_;
        }
        return FormatJSON.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatJSON json = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FormatJSON, FormatJSON.Builder, FormatJSONOrBuilder> 
        getJsonFieldBuilder() {
      if (jsonBuilder_ == null) {
        if (!(unitCase_ == 5)) {
          unit_ = FormatJSON.getDefaultInstance();
        }
        jsonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FormatJSON, FormatJSON.Builder, FormatJSONOrBuilder>(
                 (FormatJSON) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 5;
      onChanged();;
      return jsonBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        FormatCustom, FormatCustom.Builder, FormatCustomOrBuilder> customBuilder_;
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public FormatCustom getCustom() {
      if (customBuilder_ == null) {
        if (unitCase_ == 6) {
          return  (FormatCustom) unit_;
        }
        return FormatCustom.getDefaultInstance();
      } else {
        if (unitCase_ == 6) {
          return customBuilder_.getMessage();
        }
        return FormatCustom.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public Builder setCustom (FormatCustom value) {
      if (customBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        customBuilder_.setMessage(value);
      }
      unitCase_ = 6;
      return this;
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public Builder setCustom(
        FormatCustom.Builder builderForValue) {
      if (customBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        customBuilder_.setMessage(builderForValue.build());
      }
      unitCase_ = 6;
      return this;
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public Builder mergeCustom (FormatCustom value) {
      if (customBuilder_ == null) {
        if (unitCase_ == 6 &&
            unit_ != FormatCustom.getDefaultInstance()) {
          unit_ = FormatCustom.newBuilder( (FormatCustom) unit_)
              .mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        if (unitCase_ == 6) {
          customBuilder_.mergeFrom(value);
        }
        customBuilder_.setMessage(value);
      }
      unitCase_ = 6;
      return this;
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public Builder clearCustom() {
      if (customBuilder_ == null) {
        if (unitCase_ == 6) {
          unitCase_ = 0;
          unit_ = null;
          onChanged();
        }
      } else {
        if (unitCase_ == 6) {
          unitCase_ = 0;
          unit_ = null;
        }
        customBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public FormatCustom.Builder getCustomBuilder() {
      return getCustomFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    public FormatCustomOrBuilder getCustomOrBuilder() {
      if ((unitCase_ == 6) && (customBuilder_ != null)) {
        return customBuilder_.getMessageOrBuilder();
      } else {
        if (unitCase_ == 6) {
          return  (FormatCustom) unit_;
        }
        return FormatCustom.getDefaultInstance();
      }
    }
    /**
     * <code>.api.FormatCustom custom = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        FormatCustom, FormatCustom.Builder, FormatCustomOrBuilder> 
        getCustomFieldBuilder() {
      if (customBuilder_ == null) {
        if (!(unitCase_ == 6)) {
          unit_ = FormatCustom.getDefaultInstance();
        }
        customBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            FormatCustom, FormatCustom.Builder, FormatCustomOrBuilder>(
                 (FormatCustom) unit_,
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      unitCase_ = 6;
      onChanged();;
      return customBuilder_;
    }

    /**
     * <code>string protobuf = 7;</code>
     */
    public String getProtobuf() {
      Object ref = "";
      if (unitCase_ == 7) {
        ref = unit_;
      }
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (unitCase_ == 7) {
          unit_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string protobuf = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProtobufBytes() {
      Object ref = "";
      if (unitCase_ == 7) {
        ref = unit_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (unitCase_ == 7) {
          unit_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string protobuf = 7;</code>
     */
    public Builder setProtobuf(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  unitCase_ = 7;
      unit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string protobuf = 7;</code>
     */
    public Builder clearProtobuf() {
      if (unitCase_ == 7) {
        unitCase_ = 0;
        unit_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string protobuf = 7;</code>
     */
    public Builder setProtobufBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      unitCase_ = 7;
      unit_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:api.SourceDataFormat)
  }

  // @@protoc_insertion_point(class_scope:api.SourceDataFormat)
  private static final SourceDataFormat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SourceDataFormat();
  }

  public static SourceDataFormat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceDataFormat>
      PARSER = new com.google.protobuf.AbstractParser<SourceDataFormat>() {
    public SourceDataFormat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SourceDataFormat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SourceDataFormat> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SourceDataFormat> getParserForType() {
    return PARSER;
  }

  public SourceDataFormat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

