// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface TransferStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TransferStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of rows successfully loaded
   * </pre>
   *
   * <code>int64 SuccessCount = 1;</code>
   */
  long getSuccessCount();

  /**
   * <pre>
   * Number of error lines if Errorlimit is not reached
   * </pre>
   *
   * <code>int64 ErrorCount = 2;</code>
   */
  long getErrorCount();

  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   */
  java.util.List<String>
      getErrorRowsList();
  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   */
  int getErrorRowsCount();
  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   */
  String getErrorRows(int index);
  /**
   * <pre>
   * Number of rows with incorrectly-formatted data; not supported
   * </pre>
   *
   * <code>repeated string ErrorRows = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorRowsBytes(int index);
}
