// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpss.proto

package io.confluent.connect.jdbc.gp.gpss.api;

public interface UpdateOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UpdateOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  java.util.List<String>
      getMatchColumnsList();
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  int getMatchColumnsCount();
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  String getMatchColumns(int index);
  /**
   * <pre>
   * Names of the target table columns to compare when determining to update or not
   * </pre>
   *
   * <code>repeated string MatchColumns = 1;</code>
   */
  com.google.protobuf.ByteString
      getMatchColumnsBytes(int index);

  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  java.util.List<String>
      getUpdateColumnsList();
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  int getUpdateColumnsCount();
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  String getUpdateColumns(int index);
  /**
   * <pre>
   * Names of the target table columns to update if MatchColumns match
   * </pre>
   *
   * <code>repeated string UpdateColumns = 2;</code>
   */
  com.google.protobuf.ByteString
      getUpdateColumnsBytes(int index);

  /**
   * <pre>
   * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
   * </pre>
   *
   * <code>string Condition = 3;</code>
   */
  String getCondition();
  /**
   * <pre>
   * Optional additional match condition; SQL syntax and used after the 'WHERE' clause
   * </pre>
   *
   * <code>string Condition = 3;</code>
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <pre>
   * Error limit count; used by external table
   * </pre>
   *
   * <code>int64 ErrorLimitCount = 4;</code>
   */
  long getErrorLimitCount();

  /**
   * <pre>
   * Error limit percentage; used by external table
   * </pre>
   *
   * <code>int32 ErrorLimitPercentage = 5;</code>
   */
  int getErrorLimitPercentage();
}
